import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-2.5">
          <Link href="/" className="bg-blue-400 p-1.5 rounded-full">
            Home
          </Link>
          <Link href="/about" className="bg-blue-400 p-1.5 rounded-full">
            About
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
